### ISSUE TITLE
How to log the project ?

### ISSUE THREAD

**Issue by DCKT** [ajakka/react-native-here-explore#10]
Hello, 

I'm currently implementing your library (good job btw ! 😄)  and having issues with a blank map displaying only the Here logo 
![image](https://github.com/user-attachments/assets/3ba7e358-783b-465e-b31e-1c1725067e69)

I tried to check logs through `adb logcat *:S MapsView:V` but I didn't get anything. What is the right way to debug this module logs ? 

Note: I'm pretty sure it's credential issue as the `initializeHereSDK` seems to start but I would like to have more informations.

Thanks !

**Comment by ajakka** [comment]
Hey @DCKT

Have you tried the logcat inside Android Studio

Also `initializeHereSDK` returns a string that you can log to check if the initialization was successful.

**Comment by DCKT** [comment]
Hello, thanks for your answer, I setuped Android Studio and found out it was a connection issue with my enterprise VPN.
