### ISSUE TITLE
build failed SwiftEmitModule normal arm64 Emitting

### ISSUE THREAD

**Issue by ComicDread** [ajakka/react-native-here-explore#11]
Hello
i added arm64 to the excluded architectures 
now even if i remove it as it was before i get the same error.. 
any suggestion?

** BUILD FAILED **

The following build commands failed:
        SwiftEmitModule normal arm64 Emitting\ module\ for\ react_native_here_explore (in target 'react-native-here-explore' from project 'Pods')
(1 failure)

<img width="1273" alt="Screenshot 2024-07-30 alle 19 34 14" src="https://github.com/user-attachments/assets/513eed36-901c-45be-a89b-998aae9431c6">

<img width="1270" alt="Screenshot 2024-07-30 alle 19 37 27" src="https://github.com/user-attachments/assets/3fde0903-5c25-4c54-b2aa-66eba5d76a9b">

**Comment by ComicDread** [comment]
also from xcode i get an error
no such module heresdk... what?

i already deleted the chache, reinstalled node modules and pods ...

![Uploading Screenshot 2024-07-30 alle 22.04.13.png…]()

**Comment by ComicDread** [comment]
ok, my bad i don't know why xcode removed the checkbox from heresdk.xcframeowrk to the target membership.

**Comment by vlapps001** [comment]
@ComicDread How did you fix it?

**Comment by ajakka** [comment]
@vlapps001 this shouldn't be an issue in the latest version, `pod install` should fix it
