### ISSUE TITLE
Marker or at least marker image is not showing on map when releasing an apk

### ISSUE THREAD

**Issue by habhabsafi** [ajakka/react-native-here-explore#12]
I can't see any markers (or marker image) on the map when I install a release .apk
during development, after I install the app on the emulator using metro. i open the map and everything is fine and I can see the markers.
here is the code I am using 
```
            <Map
                style={{ flex: 1, }}
                mapScheme={state.scheme}
                zoomValue={zoom || 18}
                geoCoordinates={mapCenter || userCoords}
                watermarkStyle='DARK'
                bearing={state.bearing}
            >
                  <Marker
                        geoCoordinates={userCoords}
                        scale={2.0}
                        size={{ width: 40, height: 40 }}
                        anchor={{ horizontal: 0.5, vertical: 1.0 }}
                        image={require('../../../resources/img/bb_logo_1024x1024.png')}
                    />
       
            </Map>
 ```
            
 as you can see in the image below, at the center, is my marker
<img width="500" alt="Screenshot 2024-08-12 at 4 14 44 PM" src="https://github.com/user-attachments/assets/61a42026-ef8b-4c50-8fe7-a464c9b9af46">

Now when I make a release .apk and try it on the emulator or on my phone the marker doesn't show.
i do that with this command :
`adb -s <device-code> install android/app/build/outputs/apk/release/app-release.apk`
below is the same map page opened on the same emulator but this time it's a `release.apk`
<img width="555" alt="Screenshot 2024-08-12 at 4 01 00 PM" src="https://github.com/user-attachments/assets/c9795acd-fda1-4623-9c7d-675b072ade3d">
 As you can see the marker (or at least it's image) is not showing 
 
- if I use the same `adb` command but install `debug.apk` instead of `release.apk` the marker also works fine with the `debug.apk`
- also I am requiring other images for other components in the same way I am doing here -which is the same way you pointed in the documentation - and all them are showing and working fine In the `release.apk.`
- when I do an `<Image source = 'require(...)'/> with the same path I am using for the marker in the same file I am using your map, the image works in release apk

**Comment by habhabsafi** [comment]
I installed your example repo and created a release.apk and I noticed the same problem. markers are not showing with release apk but showing with debug apk only 
<img width="550" alt="Screenshot 2024-08-14 at 11 04 44 AM" src="https://github.com/user-attachments/assets/0c0b7a0e-be39-41cd-b4fa-046b8ebdde30">

**Comment by ajakka** [comment]
I will look into this

**Comment by habhabsafi** [comment]
> I will look into this

any news ?

**Comment by ajakka** [comment]
@habhabsafi checkout the latest version (2.0.2)

It should fix this issue 👍🏼

**Comment by habhabsafi** [comment]
> @habhabsafi checkout the latest version (2.0.2)
> 
> It should fix this issue 👍🏼 Could you also test if similar issue happens on iOS ?

thank you for you response and effort
I started working on the ios lately, will get back to you on that !

**Comment by habhabsafi** [comment]
i set a release build configuration for ios and tried on xcode simulator and its working
Thanks !
