### ISSUE TITLE
Build Failed on Android 

### ISSUE THREAD

**Issue by flloyddsouza** [ajakka/react-native-here-explore#14]
e: file:///C:/Users/user232/Apps/Raptor/node_modules/react-native-here-explore/android/src/main/java/com/hereexplore/features/map/MapsViewManager.kt:56:3 'addView' overrides nothing

FAILURE: Build failed with an exception.

Followed the instructions correctly. 

Gives a Build Error on addView in MapsViewManager.kt

Soloution: https://github.com/callstack/react-native-pager-view/issues/850

Its a bug in React Native 0.75.4 
can be fixed by removing ? at the end of child: View?

Previous:
 `override fun addView(parent: MapsView, child: View?, index: Int) {
    when (child) {
      is ItemView -> {
        parent.addMapItem(child)
      }
    }
  }`

Fix: `override fun addView(parent: MapsView, child: View, index: Int) {
    when (child) {
      is ItemView -> {
        parent.addMapItem(child)
      }
    }
  }`

Here SDK : heresdk-explore-android-4.20.1.0.138573.aar

"react": "18.3.1",
"react-native": "0.75.4",
 "react-native-here-explore": "2.0.2",

**Comment by ajakka** [comment]
@flloyddsouza check v2.0.3 and let me know. it should fix the issue

**Comment by ajakka** [comment]
Hey @flloyddsouza, thanks for the re
