### ISSUE TITLE
** BUILD FAILED ** iOS

### ISSUE THREAD

**Issue by ComicDread** [ajakka/react-native-here-explore#7]
Since I installed the library for iOS following the .md guide, I am receiving the following error:

The following build commands failed:
Ld /Users/andrea/Library/Developer/Xcode/DerivedData/Samichay-cwflhjrtexuuuyhhecvkanuqepaa/Build/Products/Debug-iphoneos/Samichay.app/Samichay normal (in target 'Samichay' from project 'Samichay')
(1 failure)

**Comment by ComicDread** [comment]
can it be because i left this line as default? what should i use ? 

  s.source       = { :http => 'http://example.com/heresdk.zip' }

**Comment by ajakka** [comment]
Can you try cleaning the node_modules/ and ios/Pods/ folder and reinstall them

**Comment by ComicDread** [comment]
nothing changed :(

**Comment by ComicDread** [comment]
Also android throws error.... i m sure i followed the readme correctly

 ERROR  TypeError: Cannot read property 'initializeHereSDK' of undefined, js engine: hermes

**Comment by ComicDread** [comment]
The following build commands failed:
        SwiftEmitModule normal arm64 Emitting\ module\ for\ react_native_here_explore (in target 'react-native-here-explore' from project 'Pods')
(1 failure)

**Comment by ajakka** [comment]
after pod install, did you do the linking in Xcode like shown in the screenshot here: https://github.com/ajakka/react-native-here-explore/blob/main/docs/INSTALLATION.md

**Comment by ComicDread** [comment]
Yes I noticed it had different names but yes I did it already as you said and it shows that error.

**Comment by ajakka** [comment]
I think this is just a cache issue, try clearing the cache by pressing `Shift + Command + K`
or delete derived data in your `~/Library/Developer/Xcode/DerivedData`, you do so with this command:
```zsh
rm -rf ~/Library/Developer/Xcode/DerivedData
```

and to be safe also delete the `node_modules/` and `ios/Pods/` again and re-install them.

**Comment by ComicDread** [comment]
I tried everything already and it didn't work. 
Btw it does not work even on Android! 
`ERROR  TypeError: Cannot read property 'initializeHereSDK' of undefined, js engine: hermes`

**Comment by ajakka** [comment]
Replace MapsHereConfig with HEREConfig and it should work, also you should delete the image or cut the part that shows the keys (just for safety)

**Comment by ComicDread** [comment]
am i doing something wrong? 

ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Maps`.



`import React from 'react';
import { SafeAreaView, StyleSheet } from 'react-native';
import Map from 'react-native-here-explore';;

function Maps() {


  return (
    <SafeAreaView style={styles.container} barStyle="light-content" translucent={true}>
      <Map
        mapScheme="NORMAL_NIGHT"
        zoomValue={5}
        coordinates={{ lat: 31.6913827, lon: -8.4413898 }}
      />

    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default Maps;
`
